{{- $distro := .distro -}}
{{- $suite := .suite -}}

{{- $architecture := .architecture -}}

architecture: {{ $architecture }}

actions:
  - action: apt
    description: Install base packages
    packages:
      - init
      - initramfs-tools
      - sudo

  - action: apt
    description: Install firmwares
    packages:
{{ if eq $distro "debian" }}
      - firmware-brcm80211
{{ end }}

  - action: apt
    description: Install system utilities
    packages:
      - apt-utils
      - bash-completion
      - binutils
      - file
      - gpg
      - less
      - locales
      - man-db
      - nano
      - python3
      - ssh
      - openssh-server
      - sysfsutils
      - u-boot-tools
      - wget
      - whiptail
      - xz-utils

  - action: apt
    description: Install network utilities
    packages:
      - ifupdown
      - iproute2
      - iptables
      - iputils-ping
      - iw
      - wireless-regdb
      - wpasupplicant

  - action: apt
    description: Install hardware utilities
    packages:
      - gpiod
      - i2c-tools
      - rfkill
      - usbutils

  - action: apt
    description: Install Radxa backported packages
    packages:
      - u-boot-menu

  - action: apt
    description: Install Radxa packages
    packages:
      - radxa-bootutils
      - radxa-firmware
      - rsetup
